
[build.environment]
  [build]
  command = "npm run build"
  publish = "/out"
  base = "/"
  node_version = "20.17.0"
  
  [functions]
  directory = "netlify/functions"

[[plugins]]
  package = "@netlify/plugin-functions-core"

[[scheduled-functions]]
  function = "generate-metadata"
  schedule = "0 0 * * *" # Runs daily at midnight




